[tool.poetry]
name = "safesight-control"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.12"
dearpygui = "^2.0.0"
<<<<<<< Updated upstream

=======
opencv-python = "^4.10.0.84"
requests = "^2.32.3"
pillow = "^11.0.0"
matplotlib = "^3.8.0"  
>>>>>>> Stashed changes

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
